export const SET_ACTIVE_EMAIL = "SET_ACTIVE_EMAIL";

export const DELETE_EMAIL = "DELETE_EMAIL";
export const SEND_EMAIL = "SEND_EMAIL";

export const FAVORITE_EMAIL = "FAVORITE_EMAIL";
export const UNFAVORITE_EMAIL = "UNFAVORITE_EMAIL";

export const MARK_UNREAD = "MARK_UNREAD";

export const GET_EMAILS_REQUEST = "GET_EMAILS_REQUEST";
export const GET_EMAILS_SUCCESS = "GET_EMAILS_SUCCESS";
export const GET_EMAILS_FAIL = "GET_EMAILS_FAIL";
